"""users table

Revision ID: 4d8987804359
Revises: 
Create Date: 2024-11-03 18:01:16.566354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8987804359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('long', sa.String(length=256), nullable=False),
    sa.Column('short', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_long'), ['long'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_url_short'), ['short'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_short'))
        batch_op.drop_index(batch_op.f('ix_url_name'))
        batch_op.drop_index(batch_op.f('ix_url_long'))

    op.drop_table('url')
    # ### end Alembic commands ###
