"""url table

Revision ID: cad4128c82a7
Revises: 
Create Date: 2024-11-04 13:47:50.659660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad4128c82a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('original', sa.String(length=256), nullable=False),
    sa.Column('short', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_url_original'), ['original'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_short'), ['short'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_short'))
        batch_op.drop_index(batch_op.f('ix_url_original'))
        batch_op.drop_index(batch_op.f('ix_url_name'))

    op.drop_table('url')
    # ### end Alembic commands ###
